from enum import StrEnum


class NumberType1(StrEnum):
    DIGIT = "DIGIT"
    CIRCLED_DIGIT = "CIRCLED_DIGIT"
    ROMAN_CAPITAL = "ROMAN_CAPITAL"
    ROMAN_SMALL = "ROMAN_SMALL"
    LATIN_CAPITAL = "LATIN_CAPITAL"
    LATIN_SMALL = "LATIN_SMALL"
    CIRCLED_LATIN_CAPITAL = "CIRCLED_LATIN_CAPITAL"
    CIRCLED_LATIN_SMALL = "CIRCLED_LATIN_SMALL"
    HANGUL_SYLLABLE = "HANGUL_SYLLABLE"
    CIRCLED_HANGUL_SYLLABLE = "CIRCLED_HANGUL_SYLLABLE"
    HANGUL_JAMO = "HANGUL_JAMO"
    CIRCLED_HANGUL_JAMO = "CIRCLED_HANGUL_JAMO"
    HANGUL_PHONETIC = "HANGUL_PHONETIC"
    IDEOGRAPH = "IDEOGRAPH"
    CIRCLED_IDEOGRAPH = "CIRCLED_IDEOGRAPH"